// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WkqGIQyTJ1-vi-eCSRp0UxsXZpOy0Mc',
    appId: '1:329954608340:web:a8a545f538134f0f0f6741',
    messagingSenderId: '329954608340',
    projectId: 'chat-4958d',
    authDomain: 'chat-4958d.firebaseapp.com',
    storageBucket: 'chat-4958d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hWYnYRnFFiOuZynw2-3HZsykq8FTMfY',
    appId: '1:329954608340:android:8f90aa7afa4a05450f6741',
    messagingSenderId: '329954608340',
    projectId: 'chat-4958d',
    storageBucket: 'chat-4958d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjN4eYX1S9xkx9nW1IZL21vyMM81D8w_g',
    appId: '1:329954608340:ios:7c8f005f18c7c63a0f6741',
    messagingSenderId: '329954608340',
    projectId: 'chat-4958d',
    storageBucket: 'chat-4958d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjN4eYX1S9xkx9nW1IZL21vyMM81D8w_g',
    appId: '1:329954608340:ios:7c8f005f18c7c63a0f6741',
    messagingSenderId: '329954608340',
    projectId: 'chat-4958d',
    storageBucket: 'chat-4958d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6WkqGIQyTJ1-vi-eCSRp0UxsXZpOy0Mc',
    appId: '1:329954608340:web:5ce100167af858b10f6741',
    messagingSenderId: '329954608340',
    projectId: 'chat-4958d',
    authDomain: 'chat-4958d.firebaseapp.com',
    storageBucket: 'chat-4958d.appspot.com',
  );
}
