// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHJJeQ2wf6RGGsl_IFOpOoF9wibZI6T4',
    appId: '1:162077691010:web:9e4967ef7415e39983389b',
    messagingSenderId: '162077691010',
    projectId: 'chat-fef1c',
    authDomain: 'chat-fef1c.firebaseapp.com',
    storageBucket: 'chat-fef1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALzALWf0MkhiAQr8188RC077niWd06HPQ',
    appId: '1:162077691010:android:a917057a3da9029883389b',
    messagingSenderId: '162077691010',
    projectId: 'chat-fef1c',
    storageBucket: 'chat-fef1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Yu_YSbWRBwLk5eqEk6XU3JA4n1YoUPc',
    appId: '1:162077691010:ios:bbfd8e03f46f31a283389b',
    messagingSenderId: '162077691010',
    projectId: 'chat-fef1c',
    storageBucket: 'chat-fef1c.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Yu_YSbWRBwLk5eqEk6XU3JA4n1YoUPc',
    appId: '1:162077691010:ios:bbfd8e03f46f31a283389b',
    messagingSenderId: '162077691010',
    projectId: 'chat-fef1c',
    storageBucket: 'chat-fef1c.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIHJJeQ2wf6RGGsl_IFOpOoF9wibZI6T4',
    appId: '1:162077691010:web:07bf7b3d3637b8f483389b',
    messagingSenderId: '162077691010',
    projectId: 'chat-fef1c',
    authDomain: 'chat-fef1c.firebaseapp.com',
    storageBucket: 'chat-fef1c.appspot.com',
  );
}
